name: string # Human-readable workflow name
description: string # Optional summary of the workflow
inputs: # Required user inputs
  - name: string
    type: string # string | file | number | boolean
    required: boolean # Optional, defaults to false
    secret: boolean # Optional, defaults to false
    default: string # Optional default value for the input

providers: # Optional configurations for external services like LLM providers
  - name: string # A unique, user-defined name for this provider configuration
    type: string # The type of provider (e.g. 'openai')
    api_key: string # The API key, which can be a raw string or an '{{ env.VAR }}' template

steps: # Ordered list of steps
  - id: string # Unique step ID
    uses: string # 'browser_agent' | 'shell' | 'python' | 'api'
    provider: string # (if uses: browser_agent) The name of the provider to use for this step

    browser: # (if uses: browser_agent)
      prompt: string # prompt for the agent
      upload_files: # files to upload
        - name: string
          path: string
      download_dir: string # path to target download directory
      output_schema: string # JSON schema for LLM structured output
      allowed_domains: [string] # optional list of allowed domains for the agent's navigation
      max_steps: int # optional number of max steps an agent can take. Helps control execution times and prevent infinite loops. Default 100

    run: # (if uses: shell/python)
      path: string # path to script file
      inline: string # inline script content
      interpreter: string # /bin/sh, /bin/bash, ./venv/bin/python3, etc.

    call: # (if uses: api)
      method: string # GET, POST, etc.
      url: string
      headers: map
      body: map

    if: string # Optional condition (future: templated eval)
    retry: int # Optional retries
    timeout: duration # Optional per-step timeout (e.g. 30s)
    max_failures: int # optional number of max failures a step can incur. Helps control execution times and prevent infinite loops. Default 3
