name: string # Human-readable workflow name
description: string # Optional summary of the workflow
inputs: # Required user inputs
  - name: string
    type: string # string | file | number | boolean
    required: boolean

steps: # Ordered list of steps
  - id: string # Unique step ID
    uses: string # 'browser_agent' | 'shell' | 'api' | plugin ref

    prompt: string # (if uses: browser_agent) prompt template
    upload_files: # (if uses: browser_agent) files to upload
      - name: string
        path: string
    download_dir: string # (if uses: browser_agent) path to target download directory
    output_schema: string # (if uses: browser_agent) JSON schema for LLM structured output
    allowed_domains: [string] # (if uses: browser_agent) optional list of allowed domains for the agent's navigation
    max_steps: int # (if uses: browser_agent) optional number of max steps an agent can take. Helps control execution times and prevent infinite loops. Default 100
    max_failures: int # (if uses: browser_agent) optional number of max failures an agent can incur. Helps control execution times and prevent infinite loops. Default 3

    run: # (if uses: shell) command line
      path: string
      inline: string
      shell: string

    call: # (if uses: api)
      method: string # GET, POST, etc.
      url: string
      headers: map
      body: map

    if: string # Optional condition (future: templated eval)
    retry: int # Optional retries
    timeout: duration # Optional per-step timeout (e.g. 30s)
